# Generated by Django 6.0.2 on 2026-03-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(help_text='Upload your resume/CV', upload_to='resumes/'),
        ),
    ]
