# Generated by Django 6.0.2 on 2026-03-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_application_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Job Seeker'), ('employer', 'Employer'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
